Footer
MikeKovetsky/Mindflare pull request #10
Opened 2018-08-08 10:39 UTC by Zihfred

Create footer as a section block

2018-08-08 10:47 UTC, MikeKovetsky requested changes
Не использовать css, только less файлы

2018-08-08 10:47 UTC, MikeKovetsky commented on src/index.html
> +            Be our <b>famile</b> on:
опечатка: familY

2018-08-08 10:47 UTC, MikeKovetsky commented on src/index.html
> +    <div>
Зачем этот промежуточный див?

2018-08-08 10:47 UTC, MikeKovetsky commented on src/index.html
> +              <a href=""><img src="../assets/footer/BTN%20UP1.png" alt="#"></a>
Вместо png иконок давай попробуем использовать font-awesome

2018-08-08 10:47 UTC, MikeKovetsky commented on src/index.html
> +         <div class="footer_tradeMark">
footer_tradeMark
Везде классы названы с двумя __, а тут один. Надо везде один стиль

2018-08-08 10:47 UTC, MikeKovetsky commented on src/main-scroll/css/style.css
> +.cd-section:nth-of-type(6) > div {
(опционально) переписать селектор на обычный класс. Избегать использование :nth-of-type(6) и > в дальнейшем

2018-08-08 10:47 UTC, MikeKovetsky commented on src/styles/footer.css
> +    color: white !important;
Чего !important? 
Нужно без него

2018-08-08 10:47 UTC, MikeKovetsky commented on src/styles/footer.css
> +.footer b {
Не использовать вложенные селекторы. Только bem классы

2018-08-08 10:47 UTC, MikeKovetsky commented on src/styles/footer.css
> +@media only screen and (max-width: 1000px) {
(опционально) создать переменную для 1000px
Например tablet-width

2018-08-08 11:13 UTC, Zihfred commented on src/index.html
> +    <div>
Он как-то работает с mail-scroll, когда пытаюсь убрать его и переписать все под класс, всё ломается

2018-08-11 07:13 UTC, MikeKovetsky approved these changes

2018-08-11 07:13 UTC, merged